2021/10/12 02:12:36 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/10/12 02:12:37 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/favicon.ico" (from "http://localhost/")" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/12 02:15:09 [error] 31#31: *5 FastCGI sent in stderr: "PHP message: 2021-10-12T02:15:09+00:00 [critical] Uncaught Error: syntax error, unexpected identifier "extend", expecting "{"" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/10/13 01:31:51 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/10/13 01:31:51 [error] 31#31: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/favicon.ico" (from "http://localhost/")" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/13 02:19:45 [error] 32#32: *5 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/10/13 03:40:23 [error] 32#32: *1 FastCGI sent in stderr: "PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136" while reading response header from upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/13 04:13:55 [error] 32#32: *5 FastCGI sent in stderr: "PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET http://localhost/"" at /var/www/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136
PHP message: [debug] Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::logKernelException".
PHP message: [debug] Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelException".
PHP message: [debug] Notified event "kernel.exception" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelException".
PHP message: [debug] Listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelException" stopped propagation of the event "kernel.exception".
PHP message: [debug] Listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onKernelException" was not called for event "kernel.exception".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDat
2021/10/13 04:13:56 [error] 32#32: *5 FastCGI sent in stderr: "PHP message: [info] Matched route "_wdt".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::configure".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\ValidateRequestListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\SessionListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::setDefaultLocale".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\RouterListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.request" to listener "Symfony\Component\HttpKernel\EventListener\LocaleAwareListener::onKernelRequest".
PHP message: [debug] Notified event "kernel.controller" to listener "Symfony\Bundle\FrameworkBundle\DataCollector\RouterDataCollector::onKernelController".
PHP message: [debug] Notified event "kernel.controller" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelController".
PHP message: [debug] Notified event "kernel.controller_arguments" to listener "Symfony\Component\HttpKernel\EventListener\ErrorListener::onControllerArguments".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ResponseListener::onKernelResponse".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::onKernelResponse".
PHP message: [debug] Notified event "kernel.response" to listener "Symfony\Component\HttpKernel\EventListener\ProfilerListener::onKernelResponse".
PHP mes
2021/10/25 02:45:05 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CCommentCrudController&menuIndex=2&signature=X74VTtbn0xLlzFxzyEREmT1lpprJncw63PAsbLUCuYo&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CConferenceCrudController&signature=0n11PmVegYwvxmfY2aYILYHCXL01QJOxgn2usjOwbqc"
2021/10/25 02:45:05 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CCommentCrudController&menuIndex=2&signature=X74VTtbn0xLlzFxzyEREmT1lpprJncw63PAsbLUCuYo&submenuIndex=-1"
2021/10/25 02:45:12 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:45:12 [error] 31#31: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:13 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:14 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:14 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:14 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:14 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/ HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/"
2021/10/25 02:46:31 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:31 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/25 02:46:37 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:37 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/25 02:46:40 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:41 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/25 02:46:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/25 02:46:54 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:46:54 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/25 02:47:17 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:47:17 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/25 02:47:17 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:47:17 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/25 02:47:18 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /conference/3 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/25 02:47:18 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/conference/3"
2021/10/31 20:24:12 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CConferenceCrudController&signature=0n11PmVegYwvxmfY2aYILYHCXL01QJOxgn2usjOwbqc HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/31 20:24:12 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/admin/?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CConferenceCrudController&signature=0n11PmVegYwvxmfY2aYILYHCXL01QJOxgn2usjOwbqc"
2021/10/31 20:24:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/31 20:24:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/31 20:24:50 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/31 20:24:50 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/10/31 20:24:55 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/10/31 20:24:56 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/index.php"
2021/11/01 16:13:23 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:23 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:26 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:26 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/01 16:13:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/01 16:13:28 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:50 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:50 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:51 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:51 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/10 18:15:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/11 23:19:18 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/11 23:19:18 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/11 23:19:21 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/11 23:19:21 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/"
2021/11/12 06:23:24 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Sign_up HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/12 06:23:24 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/12 06:23:27 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Sign_up HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/12 06:23:28 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/14 15:55:52 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:55:53 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:29 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:30 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:31 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:31 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:56:34 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:57:05 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:57:06 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:57:06 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 15:57:07 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/14 18:18:04 [error] 32#32: *119 FastCGI sent in stderr: "PHP message: 2021-11-14T18:18:04+00:00 [critical] Uncaught Exception: The child config "authorization_server" under "league_oauth2_server" must be configured" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:41:36 [error] 33#33: *133 FastCGI sent in stderr: "PHP message: 2021-11-15T06:41:36+00:00 [critical] Uncaught Exception: Case mismatch between loaded and declared class names: "App\utils\MomentFormatConverter" vs "App\Utils\MomentFormatConverter" in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:46:51 [error] 32#32: *136 FastCGI sent in stderr: "PHP message: 2021-11-15T06:46:51+00:00 [critical] Uncaught Exception: Case mismatch between loaded and declared class names: "App\utils\Validator" vs "App\Utils\Validator" in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:51:18 [error] 32#32: *139 FastCGI sent in stderr: "PHP message: 2021-11-15T06:51:18+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$validator" of method "__construct()" references class "App\Utils\Validator" but no such service exists. Did you mean "App\utils\Validator"?" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:51:27 [error] 32#32: *139 FastCGI sent in stderr: "PHP message: 2021-11-15T06:51:27+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$validator" of method "__construct()" references class "App\Utils\Validator" but no such service exists. Did you mean "App\utils\Validator"?" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:53:07 [error] 32#32: *143 FastCGI sent in stderr: "PHP message: 2021-11-15T06:53:07+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\ListUsersCommand": argument "$emailSender" of method "__construct()" is type-hinted "string", you should configure its value explicitly" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:56:01 [error] 32#32: *147 FastCGI sent in stderr: "PHP message: 2021-11-15T06:56:01+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\ListUsersCommand": argument "$emailSender" of method "__construct()" is type-hinted "string", you should configure its value explicitly" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 06:58:31 [error] 33#33: *149 FastCGI sent in stderr: "PHP message: 2021-11-15T06:58:31+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\ListUsersCommand": argument "$emailSender" of method "__construct()" is type-hinted "string", you should configure its value explicitly" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 07:00:00 [error] 32#32: *153 FastCGI sent in stderr: "PHP message: 2021-11-15T07:00:00+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\ListUsersCommand": argument "$emailSender" of method "__construct()" is type-hinted "string", you should configure its value explicitly" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 14:53:06 [error] 32#32: *478 FastCGI sent in stderr: "PHP message: 2021-11-15T14:53:06+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$users" of method "__construct()" has type "App\Command\UserRepository" but this class was not found" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=new&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&referrer=http%3A%2F%2Flocalhost%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26submenuIndex%3D-1&signature=uTfybeg1RbN9S7aZ6cX1pHCOden-V_6z8g5hCtkwc4A&submenuIndex=-1"
2021/11/15 14:53:35 [error] 32#32: *478 FastCGI sent in stderr: "PHP message: 2021-11-15T14:53:35+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$users" of method "__construct()" has type "App\Command\UserRepository" but this class was not found" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=new&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&referrer=http%3A%2F%2Flocalhost%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26submenuIndex%3D-1&signature=uTfybeg1RbN9S7aZ6cX1pHCOden-V_6z8g5hCtkwc4A&submenuIndex=-1"
2021/11/15 20:03:14 [error] 32#32: *975 FastCGI sent in stderr: "PHP message: 2021-11-15T20:03:14+00:00 [critical] Uncaught Exception: [Semantical Error] Couldn't find constant app_login, method App\Controller\QuestionController::signIn() in /var/www/config/routes/../../src/Controller/ (which is being imported from "/var/www/config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /Sign_in HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost"
2021/11/15 22:16:33 [error] 32#32: *1256 FastCGI sent in stderr: "PHP message: 2021-11-15T22:16:33+00:00 [critical] Uncaught Error: syntax error, unexpected token ","" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1"
2021/11/15 22:29:50 [error] 32#32: *1291 FastCGI sent in stderr: "PHP message: 2021-11-15T22:29:50+00:00 [critical] Uncaught Exception: Unrecognized option "database_users" under "security". Available options are "access_control", "access_decision_manager", "access_denied_url", "always_authenticate_before_granting", "enable_authenticator_manager", "encoders", "erase_credentials", "firewalls", "hide_user_not_found", "password_hashers", "providers", "role_hierarchy", "session_fixation_strategy"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=DESC&submenuIndex=-1"
2021/11/15 22:30:24 [error] 32#32: *1291 FastCGI sent in stderr: "PHP message: 2021-11-15T22:30:24+00:00 [critical] Uncaught Exception: Unrecognized option "database_users" under "security". Available options are "access_control", "access_decision_manager", "access_denied_url", "always_authenticate_before_granting", "enable_authenticator_manager", "encoders", "erase_credentials", "firewalls", "hide_user_not_found", "password_hashers", "providers", "role_hierarchy", "session_fixation_strategy"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=DESC&submenuIndex=-1"
2021/11/15 22:32:40 [error] 32#32: *1299 FastCGI sent in stderr: "PHP message: 2021-11-15T22:32:40+00:00 [critical] Uncaught Exception: Invalid firewall "main": user provider "app_user_provider" not found" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=DESC&submenuIndex=-1"
2021/11/15 22:33:22 [error] 32#32: *1299 FastCGI sent in stderr: "PHP message: 2021-11-15T22:33:22+00:00 [critical] Uncaught Exception: Unrecognized option "database_users" under "security.firewalls.main". Available options are "access_denied_handler", "access_denied_url", "anonymous", "context", "custom_authenticators", "entry_point", "form_login", "form_login_ldap", "guard", "host", "http_basic", "http_basic_ldap", "json_login", "json_login_ldap", "lazy", "login_link", "login_throttling", "logout", "methods", "pattern", "provider", "remember_me", "remote_user", "request_matcher", "required_badges", "security", "stateless", "switch_user", "user_checker", "x509"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=DESC&submenuIndex=-1"
2021/11/15 22:36:03 [error] 33#33: *1305 FastCGI sent in stderr: "PHP message: 2021-11-15T22:36:03+00:00 [warning] Uncaught Warning: touch(): Utime failed: No such device or address" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=DESC&submenuIndex=-1"
2021/11/15 22:39:50 [error] 33#33: *1318 FastCGI sent in stderr: "PHP message: 2021-11-15T22:39:50+00:00 [critical] Uncaught Exception: The service "security.exception_listener.main" has a dependency on a non-existent service "form_login"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1"
2021/11/15 22:40:49 [error] 33#33: *1318 FastCGI sent in stderr: "PHP message: 2021-11-15T22:40:49+00:00 [critical] Uncaught Exception: Unrecognized option "entry_point" under "security.firewalls.main.logout". Available options are "csrf_parameter", "csrf_token_generator", "csrf_token_id", "delete_cookies", "handlers", "invalidate_session", "path", "success_handler", "target"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1"
2021/11/15 22:41:31 [error] 33#33: *1318 FastCGI sent in stderr: "PHP message: 2021-11-15T22:41:31+00:00 [critical] Uncaught Exception: Unrecognized option "entry_point" under "security.firewalls.main.logout". Available options are "csrf_parameter", "csrf_token_generator", "csrf_token_id", "delete_cookies", "handlers", "invalidate_session", "path", "success_handler", "target"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1"
2021/11/15 22:42:27 [error] 33#33: *1318 FastCGI sent in stderr: "PHP message: 2021-11-15T22:42:27+00:00 [critical] Uncaught Exception: The service "security.exception_listener.main" has a dependency on a non-existent service "form_login"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1"
2021/11/15 22:43:11 [error] 33#33: *1318 FastCGI sent in stderr: "PHP message: 2021-11-15T22:43:11+00:00 [critical] Uncaught Exception: The service "security.exception_listener.main" has a dependency on a non-existent service "form_login"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1"
2021/11/15 22:43:18 [error] 33#33: *1318 FastCGI sent in stderr: "PHP message: 2021-11-15T22:43:18+00:00 [critical] Uncaught Exception: The service "security.exception_listener.main" has a dependency on a non-existent service "form_login"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1"
2021/11/15 22:43:38 [error] 33#33: *1318 FastCGI sent in stderr: "PHP message: 2021-11-15T22:43:38+00:00 [critical] Uncaught Exception: The service "security.exception_listener.main" has a dependency on a non-existent service "login"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1"
2021/11/15 22:44:05 [error] 33#33: *1318 FastCGI sent in stderr: "PHP message: 2021-11-15T22:44:05+00:00 [critical] Uncaught Exception: The service "security.exception_listener.main" has a dependency on a non-existent service "Sign_in"" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&page=1&referrer=%2Feasyadmin%3FcrudAction%3Dindex%26crudControllerFqcn%3DApp%255CController%255CEasyAdmin%255CUserCrudController%26menuIndex%3D1%26page%3D1%26signature%3DGe3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0%26sort%255Bemail%255D%3DDESC%26submenuIndex%3D-1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&sort%5Bemail%5D=ASC&submenuIndex=-1"
2021/11/15 22:50:57 [error] 33#33: *1348 FastCGI sent in stderr: "PHP message: 2021-11-15T22:50:57+00:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "html_sanitizer" (in "/var/www/config/packages/html_sanitizer.yaml"). Looked for namespace "html_sanitizer", found ""framework", "sensio_framework_extra", "twig", "web_profiler", "monolog", "debug", "maker", "doctrine", "doctrine_migrations", "security", "twig_extra", "webpack_encore", "easy_admin", "doctrine_fixtures"" in /var/www/config/packages/html_sanitizer.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1"
2021/11/15 22:51:42 [error] 33#33: *1348 FastCGI sent in stderr: "PHP message: 2021-11-15T22:51:42+00:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "html_sanitizer" (in "/var/www/config/packages/html_sanitizer.yaml"). Looked for namespace "html_sanitizer", found ""framework", "sensio_framework_extra", "twig", "web_profiler", "monolog", "debug", "maker", "doctrine", "doctrine_migrations", "security", "twig_extra", "webpack_encore", "easy_admin", "doctrine_fixtures"" in /var/www/config/packages/html_sanitizer.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1"
2021/11/15 22:51:58 [error] 33#33: *1348 FastCGI sent in stderr: "PHP message: 2021-11-15T22:51:58+00:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "html_sanitizer" (in "/var/www/config/packages/html_sanitizer.yaml"). Looked for namespace "html_sanitizer", found ""framework", "sensio_framework_extra", "twig", "web_profiler", "monolog", "debug", "maker", "doctrine", "doctrine_migrations", "security", "twig_extra", "webpack_encore", "easy_admin", "doctrine_fixtures"" in /var/www/config/packages/html_sanitizer.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1"
2021/11/15 22:52:11 [error] 33#33: *1348 FastCGI sent in stderr: "PHP message: 2021-11-15T22:52:11+00:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "html_sanitizer" (in "/var/www/config/packages/html_sanitizer.yaml"). Looked for namespace "html_sanitizer", found ""framework", "sensio_framework_extra", "twig", "web_profiler", "monolog", "debug", "maker", "doctrine", "doctrine_migrations", "security", "twig_extra", "webpack_encore", "easy_admin", "doctrine_fixtures"" in /var/www/config/packages/html_sanitizer.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1"
2021/11/15 22:54:23 [error] 32#32: *1354 FastCGI sent in stderr: "PHP message: 2021-11-15T22:54:23+00:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "html_sanitizer" (in "/var/www/config/packages/html_sanitizer.yaml"). Looked for namespace "html_sanitizer", found ""framework", "sensio_framework_extra", "twig", "web_profiler", "monolog", "debug", "maker", "doctrine", "doctrine_migrations", "security", "twig_extra", "webpack_encore", "easy_admin", "doctrine_fixtures"" in /var/www/config/packages/html_sanitizer.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1"
2021/11/15 22:56:35 [error] 33#33: *1357 FastCGI sent in stderr: "PHP message: 2021-11-15T22:56:35+00:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "html_sanitizer" (in "/var/www/config/packages/html_sanitizer.yaml"). Looked for namespace "html_sanitizer", found ""framework", "sensio_framework_extra", "twig", "web_profiler", "monolog", "debug", "maker", "doctrine", "doctrine_migrations", "security", "twig_extra", "webpack_encore", "easy_admin", "doctrine_fixtures"" in /var/www/config/packages/html_sanitizer.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1"
2021/11/15 22:58:54 [error] 32#32: *1360 FastCGI sent in stderr: "PHP message: 2021-11-15T22:58:54+00:00 [critical] Uncaught Exception: There is no extension able to load the configuration for "html_sanitizer" (in "/var/www/config/packages/html_sanitizer.yaml"). Looked for namespace "html_sanitizer", found ""framework", "sensio_framework_extra", "twig", "web_profiler", "monolog", "debug", "maker", "doctrine", "doctrine_migrations", "security", "twig_extra", "webpack_encore", "easy_admin", "doctrine_fixtures"" in /var/www/config/packages/html_sanitizer.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.22.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CUserCrudController&menuIndex=1&signature=Ge3oagAnbpJg64kwJsjZlUBdmZ9Fm_vfqsxq_D3Usv0&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.22.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1"
2021/11/17 08:25:16 [error] 32#32: *143 FastCGI sent in stderr: "PHP message: 2021-11-17T08:25:16+00:00 [critical] Uncaught Error: syntax error, unexpected token ","" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /Sign_in HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/11/17 09:12:02 [error] 34#34: *300 FastCGI sent in stderr: "PHP message: 2021-11-17T09:12:02+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$users" of method "__construct()" has type "App\Repository\UserRepository" but this class is missing a parent class (Warning: include(/var/www/vendor/composer/../../src/Repository/UserRepository.php): Failed to open stream: No such file or directory)" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78 HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/ru"
2021/11/17 09:12:26 [error] 34#34: *300 FastCGI sent in stderr: "PHP message: 2021-11-17T09:12:26+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$users" of method "__construct()" has type "App\Repository\UserRepository" but this class is missing a parent class (Warning: include(/var/www/vendor/composer/../../src/Repository/UserRepository.php): Failed to open stream: No such file or directory)" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /static/media/leader-move.c615c442.mp4 HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/leader"
2021/11/17 09:12:30 [error] 32#32: *301 FastCGI sent in stderr: "PHP message: 2021-11-17T09:12:30+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$users" of method "__construct()" has type "App\Repository\UserRepository" but this class is missing a parent class (Warning: include(/var/www/vendor/composer/../../src/Repository/UserRepository.php): Failed to open stream: No such file or directory)" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/11/17 09:12:48 [error] 32#32: *301 FastCGI sent in stderr: "PHP message: 2021-11-17T09:12:48+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Command\AddUserCommand": argument "$users" of method "__construct()" has type "App\Repository\UserRepository" but this class is missing a parent class (Warning: include(/var/www/vendor/composer/../../src/Repository/UserRepository.php): Failed to open stream: No such file or directory)" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/11/17 11:03:48 [error] 32#32: *726 FastCGI sent in stderr: "PHP message: 2021-11-17T11:03:48+00:00 [critical] Uncaught Error: syntax error, unexpected token ","" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /Sign_up HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/11/17 12:29:37 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /leader HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/11/17 12:30:04 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /leader HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/11/17 12:30:05 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: localhost, request: "GET /leader HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/11/17 13:52:52 [error] 33#33: *23 FastCGI sent in stderr: "PHP message: 2021-11-17T13:52:52+00:00 [critical] Uncaught Error: syntax error, unexpected token ":"" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /tables HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost"
2021/11/17 15:51:32 [warn] 33#33: *200 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.20.0.1, server: localhost, request: "POST /api/user_profiles/to-telegram HTTP/1.1", host: "localhost", referrer: "http://localhost/dashboard"
2021/11/17 16:17:30 [error] 33#33: *223 FastCGI sent in stderr: "PHP message: 2021-11-17T16:17:30+00:00 [critical] Uncaught Exception: [Semantical Error] Couldn't find constant name, method App\Controller\QuestionController::root() in /var/www/config/routes/../../src/Controller/ (which is being imported from "/var/www/config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled" while reading upstream, client: 172.20.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.20.0.3:9000", host: "localhost", referrer: "http://localhost/_profiler/91c849?panel=db"
2021/11/17 17:32:21 [error] 34#34: *50 FastCGI sent in stderr: "PHP message: 2021-11-17T17:32:21+00:00 [critical] Uncaught Error: Class "SymfonyCasts\Bundle\ResetPassword\SymfonyCastsResetPasswordBundle" not found" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&menuIndex=0&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78&submenuIndex=-1 HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/easyadmin?crudAction=index&crudControllerFqcn=App%5CController%5CEasyAdmin%5CPostCrudController&signature=T1auq6M3oajczxabbm5_Z5RDo4bpVfw5KfpuMlQGi78"
2021/11/17 18:29:09 [error] 33#33: *235 FastCGI sent in stderr: "PHP message: 2021-11-17T18:29:09+00:00 [critical] Uncaught Error: syntax error, unexpected token "."" while reading upstream, client: 172.18.0.1, server: localhost, request: "POST /login HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_in"
2021/11/17 18:29:14 [error] 33#33: *235 FastCGI sent in stderr: "PHP message: 2021-11-17T18:29:14+00:00 [critical] Uncaught Error: syntax error, unexpected token "."" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /Sign_in HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/17 20:01:25 [error] 33#33: *331 FastCGI sent in stderr: "PHP message: 2021-11-17T20:01:25+00:00 [critical] Uncaught Error: syntax error, unexpected token "]"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up?ref=SGUMatrix"
2021/11/17 20:48:31 [error] 33#33: *410 FastCGI sent in stderr: "PHP message: 2021-11-17T20:48:31+00:00 [critical] Uncaught Exception: [Syntax Error] Expected PlainValue, got ''' at position 28 in method App\Controller\inviterController::root() in /var/www/config/routes/../../src/Controller/ (which is being imported from "/var/www/config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up?ref=SGUMatrix"
2021/11/17 20:50:23 [error] 33#33: *416 FastCGI sent in stderr: "PHP message: 2021-11-17T20:50:23+00:00 [critical] Uncaught Exception: [Syntax Error] Expected PlainValue, got ''' at position 28 in method App\Controller\inviterController::Inviter() in /var/www/config/routes/../../src/Controller/ (which is being imported from "/var/www/config/routes/annotations.yaml"). Make sure to use PHP 8+ or that annotations are installed and enabled" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up?ref=SGUMatrix"
2021/11/18 08:54:47 [error] 33#33: *739 FastCGI sent in stderr: "PHP message: 2021-11-18T08:54:47+00:00 [critical] Uncaught Error: syntax error, unexpected token "="" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up?ref=SGUMatrix"
2021/11/18 15:25:02 [error] 33#33: *1010 FastCGI sent in stderr: "PHP message: 2021-11-18T15:25:02+00:00 [critical] Uncaught Error: syntax error, unexpected token "private", expecting "]"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/admin?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CUserProfileCrudController&signature=bkl3B63s7x4TqIyAKem9gNLJnXSIO4T1UXnWXgYzlSQ"
2021/11/18 15:26:42 [error] 33#33: *1013 FastCGI sent in stderr: "PHP message: 2021-11-18T15:26:42+00:00 [critical] Uncaught Error: syntax error, unexpected token ";", expecting "]"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/admin?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CUserProfileCrudController&signature=bkl3B63s7x4TqIyAKem9gNLJnXSIO4T1UXnWXgYzlSQ"
2021/11/18 15:28:33 [error] 33#33: *1016 FastCGI sent in stderr: "PHP message: 2021-11-18T15:28:33+00:00 [critical] Uncaught Error: syntax error, unexpected token ";", expecting "]"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/admin?crudAction=index&crudControllerFqcn=App%5CController%5CAdmin%5CUserProfileCrudController&signature=bkl3B63s7x4TqIyAKem9gNLJnXSIO4T1UXnWXgYzlSQ"
2021/11/18 16:28:25 [error] 33#33: *1115 FastCGI sent in stderr: "PHP message: 2021-11-18T16:28:25+00:00 [critical] Uncaught Error: syntax error, unexpected token "=", expecting "]"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/18 17:49:34 [error] 33#33: *1275 FastCGI sent in stderr: "PHP message: 2021-11-18T17:49:34+00:00 [critical] Uncaught Error: syntax error, unexpected token ")"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/18 17:49:39 [error] 33#33: *1275 FastCGI sent in stderr: "PHP message: 2021-11-18T17:49:39+00:00 [critical] Uncaught Error: syntax error, unexpected token ")"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/18 18:30:40 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Sign_up?ref=admin HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/18 18:30:42 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Sign_up?ref=admin HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/18 18:30:49 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Sign_up?ref=admin HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/18 18:30:59 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /inviter?username=admin HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/18 18:31:11 [error] 33#33: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/18 22:14:18 [error] 34#34: *134 FastCGI sent in stderr: "PHP message: 2021-11-18T22:14:18+00:00 [critical] Uncaught Exception: The file "../src/Controller/inviterController" does not exist (in: "/var/www/src/../config") in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/18 22:15:04 [error] 34#34: *134 FastCGI sent in stderr: "PHP message: 2021-11-18T22:15:04+00:00 [critical] Uncaught Exception: The file "./src/Controller/inviterController" does not exist (in: "/var/www/src/../config") in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/18 22:15:47 [error] 34#34: *134 FastCGI sent in stderr: "PHP message: 2021-11-18T22:15:47+00:00 [critical] Uncaught Exception: The file "../../src/Controller/inviterController" does not exist (in: "/var/www/src/../config") in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/18 22:16:56 [error] 34#34: *142 FastCGI sent in stderr: "PHP message: 2021-11-18T22:16:56+00:00 [critical] Uncaught Exception: The file "/../src/Controller/inviterController.php" does not exist in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/18 22:20:00 [error] 34#34: *148 FastCGI sent in stderr: "PHP message: 2021-11-18T22:20:00+00:00 [critical] Uncaught Exception: The file "../src/Controller/inviterController" does not exist (in: "/var/www/src/../config") in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /inviter?username=SGUMatrix HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/Sign_up"
2021/11/20 08:13:16 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:20 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:39 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:40 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:41 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:41 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:42 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:42 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:43 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:47 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 08:13:48 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/20 15:43:05 [error] 32#32: *246 FastCGI sent in stderr: "PHP message: 2021-11-20T15:43:05+00:00 [critical] Uncaught Error: syntax error, unexpected token ","" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/structure?userName=&limit=8&offset=0 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/team"
2021/11/20 15:58:47 [error] 34#34: *280 FastCGI sent in stderr: "PHP message: 2021-11-20T15:58:47+00:00 [critical] Uncaught Error: syntax error, unexpected token "]"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/structure?userName=&limit=8&offset=0 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/team"
2021/11/20 16:06:46 [error] 32#32: *317 FastCGI sent in stderr: "PHP message: 2021-11-20T16:06:46+00:00 [critical] Uncaught Error: syntax error, unexpected token "]"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/structure?userName=&limit=8&offset=0 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/team"
2021/11/20 17:25:39 [error] 32#32: *460 FastCGI sent in stderr: "PHP message: 2021-11-20T17:25:39+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Controller\structureController": argument "$userProfile" of method "__construct()" references class "App\Entity\UserProfile" but no such service exists" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/structure?userName=&limit=8&offset=0 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/team"
2021/11/20 18:33:47 [warn] 34#34: *563 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.19.0.1, server: localhost, request: "POST /api/user_profiles/avatar HTTP/1.1", host: "localhost", referrer: "http://localhost/leader"
2021/11/20 18:34:38 [warn] 34#34: *563 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000002, client: 172.19.0.1, server: localhost, request: "POST /api/user_profiles/avatar HTTP/1.1", host: "localhost", referrer: "http://localhost/leader"
2021/11/20 18:40:29 [warn] 32#32: *581 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000003, client: 172.19.0.1, server: localhost, request: "POST /api/user_profiles/avatar HTTP/1.1", host: "localhost", referrer: "http://localhost/leader"
2021/11/21 12:48:40 [error] 35#35: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/21 12:49:59 [error] 35#35: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/21 12:50:01 [error] 35#35: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/21 13:13:38 [error] 35#35: *9 FastCGI sent in stderr: "PHP message: 2021-11-21T13:13:38+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Controller\structureController": argument "$referral" of method "__construct()" references class "App\Entity\UserProfile" but no such service exists" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost"
2021/11/22 04:52:29 [error] 32#32: *178 FastCGI sent in stderr: "PHP message: 2021-11-22T04:52:29+00:00 [critical] Uncaught Error: syntax error, unexpected token "(", expecting identifier or variable or "{" or "$"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/structure?userName=&limit=8&offset=0 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/team"
2021/11/22 05:04:56 [error] 32#32: *195 FastCGI sent in stderr: "PHP message: 2021-11-22T05:04:56+00:00 [critical] Uncaught Error: syntax error, unexpected single-quoted string "$username", expecting identifier or variable or "{" or "$"" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/structure?userName=&limit=8&offset=0 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/team"
2021/11/22 06:10:53 [error] 32#32: *314 FastCGI sent in stderr: "PHP message: 2021-11-22T06:10:53+00:00 [critical] Uncaught Exception: Cannot autowire service "App\Controller\sructureController": argument "$userProfile" of method "__construct()" references class "App\Entity\UserProfile" but no such service exists" while reading upstream, client: 172.19.0.1, server: localhost, request: "GET /api/structure?userName=&limit=8&offset=0 HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "localhost", referrer: "http://localhost/team"
2021/11/22 15:23:26 [warn] 32#32: *707 a client request body is buffered to a temporary file /var/cache/nginx/client_temp/0000000001, client: 172.19.0.1, server: localhost, request: "POST /api/user_profiles/to-telegram HTTP/1.1", host: "localhost", referrer: "http://localhost/dashboard"
2021/11/24 10:12:51 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:54 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:54 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:54 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:54 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:57 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:58 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:58 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:58 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:59 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:59 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:12:59 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:00 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:00 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:00 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:00 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:00 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:01 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:01 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:01 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:01 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:01 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:01 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:02 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:02 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:02 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:03 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:03 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:03 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:03 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:03 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:04 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:04 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:04 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:04 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:04 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:04 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:05 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:05 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:05 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:05 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:05 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:06 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:06 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:06 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:06 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:07 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:07 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:07 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:07 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:07 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:08 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:08 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:08 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:08 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:08 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:09 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:09 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:10 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:10 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:11 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:11 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:11 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:11 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:12 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:12 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:24 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:24 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:25 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:25 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:25 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:25 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:26 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:26 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:27 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:36 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:37 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:37 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:38 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:38 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:39 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:39 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:39 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:40 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:40 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:40 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:40 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:40 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:41 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:41 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:41 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:41 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:42 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:42 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:42 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:42 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:43 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 10:13:43 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /dashboard HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 15:02:46 [error] 31#31: *534 FastCGI sent in stderr: "PHP message: 2021-11-24T15:02:46+00:00 [critical] Uncaught Error: syntax error, unexpected token ":", expecting "]"" while reading upstream, client: 172.18.0.1, server: localhost, request: "GET /Fate HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 17:55:11 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Fate HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 17:55:13 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Fate HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 17:57:00 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Fate HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 17:57:02 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Fate HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 17:57:03 [error] 32#32: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET /Fate HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 20:59:33 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 20:59:38 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 20:59:38 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:17 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:18 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:51 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:52 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:52 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:53 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:53 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:53 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:53 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:54 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:54 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:54 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:54 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:54 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:54 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:55 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:55 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:55 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:55 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:55 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:55 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:56 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:56 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:56 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:56 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:56 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:56 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:57 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:57 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:00:57 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:01:07 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/24 21:01:08 [error] 33#33: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/25 14:12:37 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/25 14:13:05 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/25 14:13:09 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/25 14:13:14 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/25 14:13:17 [error] 34#34: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.3:9000", host: "localhost"
2021/11/26 11:31:33 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:31:35 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:31:35 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:31:47 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:31:48 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:31:49 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:13 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:15 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:15 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:16 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:16 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:16 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:16 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:17 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:17 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:17 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:17 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:17 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:32:17 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:33:36 [error] 33#33: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:33:37 [error] 33#33: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/11/26 11:33:38 [error] 33#33: *22 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:01:35 [emerg] 1#1: host not found in upstream "php-fpm:9000" in /etc/nginx/conf.d/default.conf:2
2021/12/05 09:02:13 [error] 32#32: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:38 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:39 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:40 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:40 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:41 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:41 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:41 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:42 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:42 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:43 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:44 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:45 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:45 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:46 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/05 09:03:46 [error] 32#32: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/15 07:09:51 [error] 34#34: *2 FastCGI sent in stderr: "PHP message: 2021-12-15T07:09:51+00:00 [critical] Uncaught Error: Class "Illuminate\Database\Eloquent\Model" not found" while reading upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/18 13:07:24 [error] 32#32: *1 FastCGI sent in stderr: "PHP message: 2021-12-18T13:07:24+00:00 [critical] Uncaught Exception: Expected to find class "App\Controller\StructureController" in file "/var/www/src/Controller/StructureController.php" while importing services from resource "../src/", but it was not found! Check the namespace prefix used with the resource in /var/www/src/../config/services.yaml (which is being imported from "/var/www/src/Kernel.php")" while reading upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/26 11:42:27 [error] 32#32: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/26 12:24:50 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/26 12:24:52 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/26 12:24:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/26 12:24:53 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
2021/12/26 12:24:54 [error] 31#31: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.3:9000", host: "localhost"
